-- Versions are generated by the database, including photo and direct SQL edits.
alter table public.menu_items add column revision integer not null default 1;
alter table public.restaurants add column revision integer not null default 1;
create function public.bump_revision() returns trigger language plpgsql set search_path = '' as $$
begin new.revision := old.revision + 1; return new; end;
$$;
create trigger menu_items_revision before update on public.menu_items
for each row execute function public.bump_revision();
create trigger restaurants_revision before update on public.restaurants
for each row execute function public.bump_revision();

-- Lock the restaurant while comparing the complete menu snapshot. Concurrent additions
-- acquire the same lock via the foreign key, so a new dish cannot be silently deleted.
create function public.delete_menu_snapshot(restaurant uuid, expected jsonb)
returns table(photo_url text) language plpgsql security invoker set search_path = '' as $$
declare actual jsonb;
begin
  perform 1 from public.restaurants where id = restaurant and owner_id = auth.uid() for update;
  if not found then raise exception 'Not authorized' using errcode = '42501'; end if;
  perform 1 from public.menu_items where restaurant_id = restaurant for update;
  select coalesce(jsonb_agg(jsonb_build_object('id', id, 'revision', revision) order by id), '[]'::jsonb)
    into actual from public.menu_items where restaurant_id = restaurant;
  if actual is distinct from (select coalesce(jsonb_agg(value order by value->>'id'), '[]'::jsonb) from jsonb_array_elements(expected)) then
    raise exception 'Menu changed. Reload before deleting.' using errcode = '40001';
  end if;
  return query delete from public.menu_items where restaurant_id = restaurant returning menu_items.photo_url;
end;
$$;
revoke all on function public.delete_menu_snapshot(uuid, jsonb) from public, anon;
grant execute on function public.delete_menu_snapshot(uuid, jsonb) to authenticated;
